# SITE CONFIGURATION
title: Blog @ FreeText AI  # your site title
author: FreeText AI # You :P
description: > # Meta description of Homepage
  A blog for sharing thoughts on technology, science and insights at FreeText AI.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Your Name
  links:
    - https://twitter.com/FreeTextAI
    - https://in.linkedin.com/company/freetext-ai
    - https://github.com/freetext-ai

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'HOME', link: '/'}
  - {name: 'ABOUT', link: 'https://freetext.ai/about'}
  - {name: 'CONTACT', link: 'https://freetext.ai/contact'}

tagline: >
  Blog @ Freetext AI

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: dyuti@freetext.ai # email for form submission

twitter_username: FreeTextAI # replace with your_twitter_username or comment to remove link from footer
github_username:  freetext-ai # replace with your_github_username or comment to remove link from footer
#instagram_username: freetext-ai # replace with your_instagram_username or comment to remove link from footer

# disqus:
#   shortname: dyutibarma # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
